"""Fetch one Wikiquote page and pull the quotes out of it.

Two jobs, kept apart on purpose: `fetch_page` talks to the network and
`parse_page` never does, so the parser can be tested against saved pages and
a bad day on Wikimedia's side can't reach it.

Fetching uses the MediaWiki Action API (`action=parse`), not the REST HTML
endpoints. One request gets the rendered HTML, the revision id and the page's
title after redirects, and a missing page comes back as a JSON error instead
of a pretty HTML 404. It's also the long-stable, boring API, and I've come to
prefer boring APIs the way I prefer boring on-call weeks.

Parsing uses the standard library's `html.parser`, not BeautifulSoup. The
markup is generated by MediaWiki and balanced, so there's no tag soup to
tame, and the state we need is small: a tag stack, the current headings, how
deep in lists we are, and whether we're inside something to ignore. That
saved two new pinned packages and a lock file run. It also means we're
depending on Wikiquote's markup, which is a gentleman's agreement and not a
contract; the fixtures in `tests/fixtures/wikiquote/` are how we find out
when someone breaks it.

What a page means depends on what kind of page it is, so `parse_page` sorts
each one into a kind first:
- **work** (a film, show or game) if it has a "Cast" or "Dialogue" heading, or
  a title like "Casablanca (film)" or "Some Game (video game)" (it's a gaming
  server, so game pages get "Character, Title");
- **theme** ("Friendship") if at least three headings are a single letter A to
  Z, because theme pages are alphabetized by author;
- **author** otherwise.

The attribution comes from the page and nowhere else. If a theme page doesn't
say who said something, neither do we, and the quote is dropped.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
from dataclasses import dataclass
from html.parser import HTMLParser
from typing import Any, Literal
from urllib.parse import quote as url_quote

import httpx

from newsbot.lounge.quotes import Quote, fits
from newsbot.text import plain_line

logger = logging.getLogger(__name__)

API_URL = "https://en.wikiquote.org/w/api.php"
_PAGE_URL_PREFIX = "https://en.wikiquote.org/wiki/"

# Longer than that and it's a paragraph, not a quote of the day.
MAX_WIKIQUOTE_CHARS = 400
# Deliberately bigger than the 1 MiB cap on file and URL sources: the pages
# I checked were 123 KB and 209 KB of JSON, but the big author pages run much
# larger and I'd like them to work.
MAX_API_BYTES = 4 * 1024 * 1024
# An overall deadline, not httpx's per-operation one. A server that drips one
# byte a second never trips a per-read timeout. Module level so a test can
# shorten it instead of sleeping for ten real seconds.
FETCH_TIMEOUT_S = 10.0

_CITATION_MAX_CHARS = 150

PageKind = Literal["author", "theme", "work"]


class WikiquoteError(Exception):
    """A fetch that didn't produce a page. The message is meant to be shown to the admin."""


@dataclass(frozen=True)
class FetchedPage:
    """A page as the API returned it: the resolved title, the revision id and the rendered HTML."""

    title: str
    revid: int
    html: str


@dataclass(frozen=True)
class ParsedPage:
    """What `parse_page` found, plus how many quotes it turned away and why."""

    kind: PageKind
    quotes: list[Quote]
    dropped_long: int
    dropped_unattributed: int


def page_url(title: str) -> str:
    """The page's address, built only from `urllib.parse.quote` output.

    That's what makes it safe to post unescaped inside `<...>`: `quote()`
    can't emit a `>`, a space or a backtick. `(`, `'` and `,` stay literal
    because Wikiquote's own URLs leave them alone.
    """
    return _PAGE_URL_PREFIX + url_quote(title.replace(" ", "_"), safe="()',")


# --- Fetching ---


async def fetch_page(http: httpx.AsyncClient, title: str) -> FetchedPage:
    """Fetch `title` from the MediaWiki API, following on-wiki redirects.

    Uses the shared client, so the contact-bearing user agent comes with it.
    Doesn't retry: a failure means the caller falls back to its saved copy.

    Raises:
        WikiquoteError: on a timeout, a network failure, a non-200 status
            (redirects included, since the API shouldn't send any), a
            response that isn't JSON or is over `MAX_API_BYTES`, an API
            error (a missing page gets its own message), or an unexpected
            response shape.
    """
    params = {
        "action": "parse",
        "format": "json",
        "formatversion": "2",
        "redirects": "1",
        "prop": "text|revid|displaytitle",
        "disableeditsection": "1",
        "disablelimitreport": "1",
        "disabletoc": "1",
        "page": title,
    }
    try:
        async with asyncio.timeout(FETCH_TIMEOUT_S):
            body = await _get_body(http, params)
    except TimeoutError as exc:
        raise WikiquoteError(f"Wikiquote didn't answer within {FETCH_TIMEOUT_S:g} seconds") from exc
    except httpx.HTTPError as exc:
        # str() of an httpx timeout is empty, so the class name does the talking.
        raise WikiquoteError(f"couldn't reach Wikiquote ({type(exc).__name__})") from exc
    except (UnicodeError, httpx.InvalidURL, httpx.StreamError) as exc:
        # These aren't HTTPErrors. The usual culprit is a title httpx can't
        # encode (a lone surrogate; only a hand-escaped config value gets
        # there), and a fetch that raises anything but WikiquoteError is a
        # fetch whose caller has to guess.
        raise WikiquoteError(
            f"couldn't send the request to Wikiquote ({type(exc).__name__})"
        ) from exc
    return _unwrap(title, body)


async def _get_body(http: httpx.AsyncClient, params: dict[str, str]) -> bytes:
    """GET the API and return the body, enforcing status, content type and size."""
    async with http.stream(
        "GET", API_URL, params=params, follow_redirects=False, timeout=FETCH_TIMEOUT_S
    ) as response:
        status = response.status_code
        if 300 <= status < 400:
            raise WikiquoteError(f"Wikiquote's API answered with a redirect (HTTP {status})")
        if status != 200:
            raise WikiquoteError(f"Wikiquote's API returned HTTP {status}")
        media_type = response.headers.get("content-type", "").split(";")[0].strip().lower()
        if media_type != "application/json":
            raise WikiquoteError(
                f"Wikiquote's API answered with {media_type or 'no content type'}, not JSON"
            )
        chunks: list[bytes] = []
        total = 0
        async for chunk in response.aiter_bytes():
            total += len(chunk)
            if total > MAX_API_BYTES:
                raise WikiquoteError(
                    f"Wikiquote's response is over {MAX_API_BYTES // (1024 * 1024)} MiB"
                )
            chunks.append(chunk)
        return b"".join(chunks)


def _unwrap(title: str, body: bytes) -> FetchedPage:
    """Turn the API's JSON into a `FetchedPage`, or a `WikiquoteError` saying what it said."""
    try:
        data: Any = json.loads(body)
    except ValueError as exc:
        raise WikiquoteError("Wikiquote's response wasn't valid JSON") from exc
    except RecursionError as exc:
        # About 100k nested brackets fit in well under the size cap, and the
        # stdlib parser answers with a RecursionError instead of a ValueError.
        raise WikiquoteError("Wikiquote's response was nested too deeply to read") from exc
    if not isinstance(data, dict):
        raise WikiquoteError("Wikiquote's response wasn't a JSON object")

    # The standard Action API error envelope is {"error": {"code", "info"}}.
    # Confirmed from memory of the MediaWiki "API:Errors and warnings" page
    # (the default errorformat, "bc"), not from a live request.
    error = data.get("error")
    if error is not None:
        code = error.get("code") if isinstance(error, dict) else None
        info = error.get("info") if isinstance(error, dict) else None
        if code == "missingtitle":
            raise WikiquoteError(f"Wikiquote has no page called {title} (renamed or deleted?)")
        if code == "invalidtitle":
            raise WikiquoteError(f"{title} isn't a valid Wikiquote page title")
        if code is None and info is None:
            # {"error": "boom"} and friends: nothing usable inside, and the
            # raw body isn't ours to echo.
            raise WikiquoteError("Wikiquote returned an error it didn't explain")
        # Both fields are the server's words, so both get one line and a cap
        # (Discord's limit is 2,000 characters; the response's is 4 MiB).
        # plain_line, not first_line: the info text is prose that can hold
        # `&` and `<`, and it shouldn't be "cleaned" into something it wasn't.
        said = [
            plain_line(str(part), limit)
            for part, limit in ((code, 100), (info, 250))
            if part is not None
        ]
        raise WikiquoteError("Wikiquote said " + ": ".join(said))

    parse = data.get("parse")
    if not isinstance(parse, dict):
        raise WikiquoteError("Wikiquote's response had no page in it")
    resolved, revid, html = parse.get("title"), parse.get("revid"), parse.get("text")
    if not (isinstance(resolved, str) and isinstance(revid, int) and isinstance(html, str)):
        raise WikiquoteError("Wikiquote's response was missing the title, revision or text")
    return FetchedPage(resolved, revid, html)


# --- Parsing ---

# Elements whose whole subtree is noise: markup that isn't text, tables,
# figures (a caption is a pull-quote with no speaker) and reference markers.
_IGNORED_TAGS = frozenset({"style", "script", "table", "figure", "sup"})
_IGNORED_CLASSES = frozenset(
    {"noprint", "navbox", "references", "mw-references-wrap", "references-small", "mw-editsection"}
)
_VOID_TAGS = frozenset(
    {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source"}
    | {"track", "wbr"}
)
_LISTS = frozenset({"ul", "ol", "dl"})
_HEADING_LEVELS = {"h2": 2, "h3": 3, "h4": 4}

# A heading matching this, and everything below it until the next heading at
# the same or a higher level, is skipped. "Attributed" is in there on
# purpose: those are secondhand reports, and we post attributions as fact.
# The `\b` keeps "Cast" from eating a heading like "Castiel".
_SKIP_HEADING_RE = re.compile(
    r"(?:disputed|misattributed|attributed|quotes about|about|said about|external links"
    r"|see also|notes|references|sources|bibliography|further reading|cast|taglines)\b",
    re.IGNORECASE,
)
# Headings that name a section, not a speaker or a work, so they don't belong in an attribution.
_GENERIC_HEADINGS = frozenset({"quotes", "sourced", "quotations", "dialogue"})
_WORK_TITLE_RE = re.compile(r"\(([^)]*)\)\s*$")
_WORK_WORD_RE = re.compile(r"\b(?:film|tv|series|video game)\b", re.IGNORECASE)


@dataclass
class _Raw:
    """A quote as found, before the page kind decides how to attribute it."""

    text: str
    cite: str | None
    headings: list[str]
    dialogue: bool


def _one_line(parts: list[str]) -> str:
    return " ".join("".join(parts).split())


def _lines(parts: list[str]) -> str:
    """Join text parts: whitespace collapsed within lines, blank lines dropped, `<br>` kept."""
    lines = (" ".join(line.split()) for line in "".join(parts).split("\n"))
    return "\n".join(line for line in lines if line)


class _PageParser(HTMLParser):
    """Walks the page once and collects `_Raw` quotes and every heading it saw.

    The stack holds open tags. An end tag pops back to the matching open tag
    (an unmatched one is ignored), and anything that was open inside what got
    popped is closed with it, so a stray tag can confuse one quote and not
    the rest of the page. Quote text is collected only at the list depth it
    belongs to, which is how a nested citation stays out of its quote's text.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.raw: list[_Raw] = []
        self.headings_seen: list[tuple[int, str]] = []

        self._stack: list[str] = []
        # Bookkeeping so no tag has to scan the whole stack. The first version
        # did (`tag in stack`, a filtered copy for every list check) and a
        # page of 30,000 unclosed <li>s took 54 seconds, because I assumed
        # Wikimedia's markup would always close what it opens. It doesn't
        # have to, and a hostile page certainly won't. Now every tag is
        # pushed once and popped once, and everything else is a lookup.
        self._open_at: dict[str, list[int]] = {}
        self._list_at: list[int] = []
        self._ignore_from: int | None = None
        self._chain: list[tuple[int, str]] = []
        self._seen_h2 = False
        self._skip_level: int | None = None

        self._heading_at: int | None = None
        self._heading_level = 0
        self._heading_parts: list[str] = []

        self._item_at: int | None = None
        self._item_parts: list[str] = []
        self._item_headings: list[str] = []
        self._item_cite: str | None = None
        self._cite_at: int | None = None
        self._cite_parts: list[str] = []
        self._cite_done = False

        self._dl_at: int | None = None
        self._dl_lines: list[str] = []
        self._dl_headings: list[str] = []
        self._dd_at: int | None = None
        self._dd_parts: list[str] = []

    # -- HTMLParser hooks --

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        ignoring = self._ignore_from is not None
        if tag in _VOID_TAGS:
            if not ignoring:
                self._void(tag)
            return
        index = len(self._stack)
        if not ignoring:
            if self._is_ignored(tag, attrs):
                self._ignore_from = index
            else:
                self._open(tag, index)
        self._open_at.setdefault(tag, []).append(index)
        if tag in _LISTS:
            self._list_at.append(index)
        self._stack.append(tag)

    def handle_endtag(self, tag: str) -> None:
        if tag in _VOID_TAGS or not self._open_at.get(tag):
            return
        self._unwind(self._open_at[tag][-1])

    def handle_data(self, data: str) -> None:
        if self._ignore_from is not None:
            return
        sink = self._sink()
        if sink is not None:
            sink.append(data)

    # -- State --

    def _lists(self) -> list[str]:
        """The three outermost open lists' tags, which is all any caller compares.

        Capped so it stays constant-time however deep the nesting goes: a
        fourth list can't change any answer, since every check is against a
        shorter list.
        """
        return [self._stack[i] for i in self._list_at[:3]]

    def _counting(self) -> bool:
        """True where quotes count: after the first h2, outside a skipped section."""
        return self._seen_h2 and self._skip_level is None

    def _context(self) -> list[str]:
        return [t for _, t in self._chain if t and t.lower() not in _GENERIC_HEADINGS]

    def _sink(self) -> list[str] | None:
        """Where text at this moment belongs, if anywhere."""
        if self._heading_at is not None:
            return self._heading_parts
        lists = self._lists()
        if self._dd_at is not None and lists == ["dl"]:
            return self._dd_parts
        if self._cite_at is not None and lists == ["ul", "ul"]:
            return self._cite_parts
        if self._item_at is not None and lists == ["ul"]:
            return self._item_parts
        return None

    @staticmethod
    def _is_ignored(tag: str, attrs: list[tuple[str, str | None]]) -> bool:
        if tag in _IGNORED_TAGS:
            return True
        classes = set(dict(attrs).get("class", "").split())
        return bool(classes & _IGNORED_CLASSES) or (tag == "a" and "autonumber" in classes)

    def _void(self, tag: str) -> None:
        sink = self._sink()
        if tag == "br" and sink is not None:
            sink.append("\n")
        elif tag == "hr":
            # An <hr> between exchanges normally sits outside any <dl>; if it
            # ever lands inside one, it still ends the exchange.
            self._flush_dl()

    def _open(self, tag: str, index: int) -> None:
        if tag in _HEADING_LEVELS:
            self._heading_at, self._heading_level, self._heading_parts = (
                index,
                _HEADING_LEVELS[tag],
                [],
            )
        elif tag == "li":
            lists = self._lists()
            if lists == ["ul"] and self._counting():
                if self._item_at is not None:
                    self._end_item()
                self._item_at, self._item_parts = index, []
                self._item_headings, self._item_cite = self._context(), None
                self._cite_done = False
            elif lists == ["ul", "ul"] and self._item_at is not None:
                if not self._cite_done and self._cite_at is None:
                    self._cite_at, self._cite_parts = index, []
        elif tag == "dl":
            if not self._lists() and self._counting() and self._dl_at is None:
                self._dl_at, self._dl_lines, self._dl_headings = index, [], self._context()
        elif tag == "dd":
            if self._lists() == ["dl"] and self._dl_at is not None and self._dd_at is None:
                self._dd_at, self._dd_parts = index, []

    def _unwind(self, index: int) -> None:
        """Close everything opened at or after stack position `index`."""
        if self._heading_at is not None and self._heading_at >= index:
            self._end_heading()
        if self._dd_at is not None and self._dd_at >= index:
            self._end_dd()
        if self._cite_at is not None and self._cite_at >= index:
            self._end_cite()
        if self._item_at is not None and self._item_at >= index:
            self._end_item()
        if self._dl_at is not None and self._dl_at >= index:
            self._end_dl()
        if self._ignore_from is not None and self._ignore_from >= index:
            self._ignore_from = None
        for i in range(len(self._stack) - 1, index - 1, -1):
            self._open_at[self._stack[i]].pop()
        while self._list_at and self._list_at[-1] >= index:
            self._list_at.pop()
        del self._stack[index:]

    def _end_heading(self) -> None:
        level, text = self._heading_level, _one_line(self._heading_parts)
        self._heading_at = None
        self.headings_seen.append((level, text))
        self._seen_h2 = self._seen_h2 or level == 2
        if self._skip_level is not None and level <= self._skip_level:
            self._skip_level = None
        self._chain = [h for h in self._chain if h[0] < level] + [(level, text)]
        if self._skip_level is None and _SKIP_HEADING_RE.match(text):
            self._skip_level = level

    def _end_cite(self) -> None:
        text = _one_line(self._cite_parts)
        if len(text) > _CITATION_MAX_CHARS:
            text = text[: _CITATION_MAX_CHARS - 1].rstrip() + "…"
        self._item_cite = text or None
        self._cite_at, self._cite_done = None, True

    def _end_item(self) -> None:
        text = _lines(self._item_parts)
        if text:
            self.raw.append(_Raw(text, self._item_cite, self._item_headings, dialogue=False))
        self._item_at = None
        self._cite_at = None

    def _end_dd(self) -> None:
        line = _one_line(self._dd_parts)
        if line:
            self._dl_lines.append(line)
        self._dd_at = None

    def _flush_dl(self) -> None:
        if self._dl_at is not None and self._dl_lines:
            self.raw.append(_Raw("\n".join(self._dl_lines), None, self._dl_headings, dialogue=True))
        self._dl_lines = []

    def _end_dl(self) -> None:
        self._flush_dl()
        self._dl_at = None


def _page_kind(title: str, headings: list[tuple[int, str]]) -> PageKind:
    if any(level == 2 and text.lower() in {"cast", "dialogue"} for level, text in headings):
        return "work"
    parenthetical = _WORK_TITLE_RE.search(title)
    if parenthetical and _WORK_WORD_RE.search(parenthetical.group(1)):
        return "work"
    if sum(1 for _, text in headings if re.fullmatch(r"[A-Z]", text)) >= 3:
        return "theme"
    return "author"


def _attribution(kind: PageKind, title: str, raw: _Raw) -> str | None:
    """Build the attribution for one quote, every part of it taken from the page."""
    if kind == "theme":
        return raw.cite
    if kind == "work":
        return ", ".join([*raw.headings, title])
    return ", ".join([title, *raw.headings, *([raw.cite] if raw.cite else [])])


def parse_page(title: str, html: str) -> ParsedPage:
    """Parse a Wikiquote page's rendered HTML into quotes with attributions.

    `title` should be the API's resolved title (`FetchedPage.title`); it
    becomes part of the attribution and the page link. Quotes over
    `MAX_WIKIQUOTE_CHARS`, or too long for a Discord message once rendered,
    are dropped and counted in `dropped_long`. On a theme page a quote with no
    citation is dropped and counted in `dropped_unattributed`.
    """
    parser = _PageParser()
    parser.feed(html)
    parser.close()

    kind = _page_kind(title, parser.headings_seen)
    logger.info("Wikiquote page %r looks like a %s page", title, kind)
    link = page_url(title)

    quotes: list[Quote] = []
    dropped_long = dropped_unattributed = 0
    for raw in parser.raw:
        # Dialogue only means something on a work page; on the others a <dl>
        # is "Full text online" or "Quotes reported in", not a quote.
        if raw.dialogue and kind != "work":
            continue
        attribution = _attribution(kind, title, raw)
        if kind == "theme" and not attribution:
            dropped_unattributed += 1
            continue
        quote = Quote(raw.text, attribution, link)
        # json.loads happily hands over a lone surrogate, which can't be
        # UTF-16 encoded, so fits() would raise. Nobody can post it anyway;
        # it goes in the "too long" pile with the other quotes we can't send.
        try:
            sendable = len(raw.text) <= MAX_WIKIQUOTE_CHARS and fits(quote)
        except UnicodeEncodeError:
            sendable = False
        if not sendable:
            dropped_long += 1
            continue
        quotes.append(quote)
    return ParsedPage(kind, quotes, dropped_long, dropped_unattributed)
